### ISSUE TITLE
feat: change data from files

### ISSUE THREAD

**Issue by efureev** [tarampampam/mustpl#4]
feats, I need:
- change template data from other files.
- import a file into template.

E.g.:
```json
{
"endpoints":[
    {{ import ./content/end1.json }},
    {{ import ./content/end2.json }}
]
}
```

```json
{
"host": "{{ import ./dev/vars.json | env.host }}"
}
```

**Comment by tarampampam** [comment]
@efureev Is that what you need? https://gitlab.com/jobol/mustach/-/blob/master/test5/must#L3

![image](https://user-images.githubusercontent.com/7326800/200822192-6cef648f-f8a4-4f55-bca2-c519a39edcdc.png)
![image](https://user-images.githubusercontent.com/7326800/200822282-40e52d25-8cdc-4bd2-a72b-4e66915bd87f.png)
![image](https://user-images.githubusercontent.com/7326800/200822532-8b4d87f1-9a33-4af2-adeb-32ee1db34d19.png)

**Comment by efureev** [comment]
yes. thx
